# Change these first
owner: cincinnatilibrary # Your GitHub organization or username, where this repository lives
repo:  uptime-reports # The name of this repository
assignees:
  - rayvoelker

sites:
  - name: CHPL Classic WebPAC (Public Access Catalog)  
    url: https://classic.cincinnatilibrary.org/
  - name: CHPL Sierra REST API
    url: https://classic.cincinnatilibrary.org/iii/sierra-api/about
  - name: CHPL Encore Discovery Layer
    url: https://catalog.cincinnatilibrary.org
  - name: CHPL Remote Databases / EZProxy
    url: https://login.research.cincinnatilibrary.org/login
  - name: CHPL Main Web Site / BiblioWeb
    url: https://cincinnatilibrary.org/
  - name: CHPL Discovery Layer / BiblioCore
    url: https://cincinnatilibrary.bibliocommons.com
  - name: CHPL libcal
    url: https://cincinnatilibrary.libcal.com/
  - name: Collection Analysis Datasette
    url: https://collection-analysis.cincy.pl/
  - name: Newsdex
    url: http://newsdex.chpl.org/
    
status-website:
  baseUrl: /uptime-reports # where "repo" is your repository name
  name: CHPL Uptime-Reports -- Web Services Status Website
  logoUrl: https://raw.githubusercontent.com/plch/brand-and-logos/master/CHPL_Brandmark_Primary.png

# status-website:
#   # Add your custom domain name, or remove the `cname` line if you don't have a domain
#   # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
# #   cname: demo.upptime.js.org
#   # baseUrl: /your-repo-name
#   logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
#   name: Upptime
#   introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
#   introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
#   navbar:
#     - title: Status
#       href: /
#     - title: GitHub
#       href: https://github.com/$OWNER/$REPO

# # Upptime also supports notifications, assigning issues, and more
# # See https://upptime.js.org/docs/configuration
